name = "iptv-worker"
main = "src/index.js"
compatibility_date = "2024-05-01"
workers_dev = true

[vars]
M3U_URL = "https://raw.githubusercontent.com/zerodayip/Py/refs/heads/main/m3u8/playlist2.m3u"
USERS_URL = "https://raw.githubusercontent.com/zerodayip/denemeler/refs/heads/main/users.json"

[triggers]
crons = []

[env.production]
name = "iptv-worker-prod"
