name = "iptv-worker"
main = "index.js"
compatibility_date = "2025-05-23"
# env secret olarak GH_TOKEN tanımlı, kodda doğrudan yazma

[vars]
# Varsayılan değişkenler, genelde kullanılmıyor çünkü GH_TOKEN secret olarak var.

[build]
command = ""

[triggers]
# Eğer otomatik tetikleme gerekiyorsa buraya yazılır
